// Optional DOM integration check: node test_map_dom.js GENERATED_HTML JSDOM_MODULE
// JSDOM is a development-only tool and is not installed with the Python product.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const {JSDOM, VirtualConsole} = require(process.argv[3] || 'jsdom');
const errors = [];
const consoleCapture = new VirtualConsole();
consoleCapture.on('jsdomError', error => errors.push(error.message));
const dom = new JSDOM(fs.readFileSync(process.argv[2], 'utf8'), {
  runScripts:'outside-only', virtualConsole:consoleCapture,
});
const w = dom.window, d = w.document;
// Execute only the viewer authored and bundled by this project. No resource loading.
const scripts = Array.from(d.querySelectorAll('script')).filter(s=>s.type !== 'application/json');
assert.equal(scripts.length, 1);
w.eval(scripts[0].textContent);
const ids = () => Array.from(d.querySelectorAll('#drawing g[data-node-id]'), n=>n.dataset.nodeId);
const event = id => d.getElementById(id).dispatchEvent(new w.Event('change'));
const mixed=process.argv.includes('--mixed');
assert.equal(d.getElementById('mode').value, 'structure');
d.getElementById('mode').value='relations';event('mode');
assert.deepEqual(ids(), mixed ? ['file:a.py','file:b.py','file:web/app.js','file:web/core.js','file:web/core.ts'] : ['file:a.py','file:b.py']);
const mapData=JSON.parse(d.getElementById('map-data').textContent);
const fileCall=mapData.file_edges.find(e=>e.kind==='call'&&e.source==='file:b.py'&&e.target==='file:a.py');
assert.ok(fileCall);
d.querySelector('#drawing g[data-node-id="file:a.py"]').dispatchEvent(new w.Event('click'));
assert.deepEqual(ids(), ['file:a.py','file:b.py']);
assert.ok(d.querySelector(`#drawing path[data-edge-id="${fileCall.id}"]`), 'A selected file keeps its cross-file call');
const callFilter = d.querySelector('input[value="call"]');
callFilter.checked = false; callFilter.dispatchEvent(new w.Event('change'));
assert.equal(d.querySelectorAll('#drawing path[data-edge-id]').length, 2);
callFilter.checked = true; callFilter.dispatchEvent(new w.Event('change'));
d.getElementById('tests').checked = true; event('tests');
assert.ok(ids().includes('file:test_a.py'));
d.getElementById('tests').checked = false; event('tests');
d.getElementById('search').value = 'target';
d.getElementById('search').dispatchEvent(new w.Event('input'));
const target = Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='target');
assert.ok(target); target.click();
assert.ok(ids().includes('symbol:a.py::target'));
assert.ok(ids().includes('symbol:b.py::run'));
assert.ok(d.getElementById('selection').textContent.includes('a.py:1'));
d.getElementById('search').value='';d.getElementById('search').dispatchEvent(new w.Event('input'));
d.getElementById('reset').click();
d.getElementById('mode').value='structure';event('mode');
const fileButton=Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='a.py');
fileButton.click();
assert.ok(ids().includes('symbol:a.py::Box'));
const classButton=Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='Box');
classButton.click();
assert.ok(ids().includes('symbol:a.py::Box.go'));
const before=d.querySelector('#drawing svg').getAttribute('viewBox');
d.getElementById('zoom-in').click();
assert.notEqual(d.querySelector('#drawing svg').getAttribute('viewBox'),before);
d.getElementById('fit').click();
d.getElementById('search').value='pkg/deep';
d.getElementById('search').dispatchEvent(new w.Event('input'));
const deepButton=Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='deep');
assert.ok(deepButton);deepButton.click();
assert.equal(d.getElementById('mode').value,'structure');
assert.ok(ids().includes('dir:pkg/deep'),'Directory search must show the selected directory');
assert.ok(ids().includes('file:pkg/deep/README.md'),'Directory search must open the selected directory');
assert.ok(!ids().includes('file:other/README.md'),'Directory search must keep unrelated directories closed');
const selectedDirectory=d.querySelector('#drawing g[data-node-id="dir:pkg/deep"]');
assert.equal(selectedDirectory.querySelector('rect').getAttribute('stroke'),'#2563eb','Directory search must highlight its target');
const camera=d.querySelector('#drawing svg').getAttribute('viewBox').split(' ').map(Number);
const selectedY=Number(selectedDirectory.getAttribute('transform').match(/translate\([^,]+,([^\)]+)\)/)[1]);
assert.ok(camera[1]>0,'Directory search must move the camera to a distant target');
assert.ok(selectedY>=camera[1]&&selectedY+mapData.layout.node_height<=camera[1]+camera[3],'Selected directory must be in the camera viewport');
if(mixed){
  d.getElementById('search').value='web/core.ts::target';
  d.getElementById('search').dispatchEvent(new w.Event('input'));
  const ts=Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='target');
  assert.ok(ts);ts.click();
  assert.ok(ids().includes('symbol:web/core.ts::target'));
  d.getElementById('mode').value='structure';event('mode');
  assert.ok(ids().includes('dir:web'),'Selecting a TS symbol must expand its ancestors');
  assert.ok(ids().includes('file:web/core.ts'));
  d.getElementById('reset').click();
  d.getElementById('search').value='web/core.js';
  d.getElementById('search').dispatchEvent(new w.Event('input'));
  const js=Array.from(d.querySelectorAll('#node-list .choose')).find(n=>n.textContent==='core.js');
  assert.ok(js);js.click();
  d.getElementById('mode').value='relations';event('mode');
  assert.deepEqual(ids(),['file:web/core.js','file:web/app.js']);
  const jsCall=mapData.file_edges.find(e=>e.kind==='call'&&e.source==='file:web/app.js');
  assert.ok(jsCall&&d.querySelector(`#drawing path[data-edge-id="${jsCall.id}"]`));
}
let exported;
w.URL.createObjectURL = blob => {exported=blob;return 'blob:controlled-test';};
w.URL.revokeObjectURL = () => {};
w.HTMLAnchorElement.prototype.click = () => {};
d.getElementById('export').click();
assert.ok(exported);
(async()=>{
  const text=await new Promise((resolve,reject)=>{const reader=new w.FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsText(exported);});
  const svg=new JSDOM(text,{contentType:'image/svg+xml'});
  assert.deepEqual(Array.from(svg.window.document.querySelectorAll('g[data-node-id]'), n=>n.dataset.nodeId),ids());
  assert.ok(svg.window.document.documentElement.textContent.includes('源码'));
  assert.ok(!svg.window.document.querySelector('script'));
  assert.deepEqual(errors,[]);
  console.log('DOM: initial graph, filters, search, nested expansion, zoom, current SVG serialization passed');
  dom.window.close(); svg.window.close();
})().catch(error=>{console.error(error);process.exitCode=1;dom.window.close();});
